// import Link from 'next/link';
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// // const geistSans = Geist({
// //   variable: "--font-geist-sans",
// //   subsets: ["latin"],
// // });

// // const geistMono = Geist_Mono({
// //   variable: "--font-geist-mono",
// //   subsets: ["latin"],
// // });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body>
//         <div>
//           <Link href={"/Channel"}>Home</Link>
//           <Link href={"/myyoutube"}>myYoutube</Link>
//           <Link href={"/fghskjjk"}>Other Channel</Link>
//         </div>
//         {children}
//       </body>
//     </html>
//   );
// }

// layout.js
import './globals.css';
import Link from 'next/link';

export const metadata = {
  title: 'My Channel',
  description: 'My Awesome YouTube Community',
};

export default function RootLayout({ children }) {
  return (
    
      <body>
        <nav className="navbar">
          <Link href="/">Home</Link>
          <Link href="/myYoutube">YouTube</Link>
          <Link href="/myYoutube/myCommunity">Community</Link>
        </nav>
        <main className="main-content">
          {children}
        </main>
      </body>
    
  );
}