/*export const metadata = {
  title: "YouTube Channel",
  description: "Generated by create next app",
};*/


import ChannelComp from "../components/channelcomp";
import NotFound from "../not-found";

export default function Channel({ params }) {
  
  return (
    <div>
      {/* <h1>My channel name is:</h1>
      <ChannelComp></ChannelComp> */}
      <NotFound/>
    </div>
  );
}